version: 1
app: begam-in
kind: static
static_root: /home/kyle/websites/begam.in

routes:
  - domain: begam.in
  - domain: www.begam.in

verify:
  - name: landing
    url: https://begam.in/
  - name: www-landing
    url: https://www.begam.in/
